name: Build libXray

on:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build Android package
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build Android
        run: |
          python3 build/main.py android
          ls
      - uses: actions/upload-artifact@v4
        with:
          name: libXray.aar
          path: ./libXray.aar
  build-ios:
    name: Build IOS and TVos package
    runs-on: macos-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Xcode Command Line Tools
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install iOS and tvOS Simulator Runtimes
        run: |
          xcversion simulators --install="iOS Simulator Runtime"
          xcversion simulators --install="tvOS Simulator Runtime"

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Compile for Apple devices
        run: python3 build/main.py apple go

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apple-binaries
          path: |
            *.xcframework
            *.h
          if-no-files-found: error

      - name: Generate bridging header
        run: |
          echo "// Bridging Header for Swift" > bridging-header.h
          echo "#import \"your_generated_header.h\"" >> bridging-header.h

      - name: Upload bridging header
        uses: actions/upload-artifact@v3
        with:
          name: bridging-header
          path: bridging-header.h
